### PR TITLE
Favourite movie

### PR DESCRIPTION
**Pull request by BrijneetaGupta**

### CODE REVIEW

**Review by Avinash9694 — APPROVED** [review]
console.log("code looks fine!")

**Comment by BrijneetaGupta** [comment]
> console.log("code looks fine!")

document.write("Thanks!");
document.close();

**Comment by Abduliitr** [comment]
The code is working fine. But `pop()` doesn't need any argument here.

Tests: 4 passed, 4 total

**Comment by BrijneetaGupta** [comment]
> The code is working fine. But `pop()` doesn't need any argument.
> 
> Tests: 4 passed, 4 total

Okay sir. Will take care of that.

**Pull request merged**
